_target_: definitions.FLAVAArguments
training:
  _target_: definitions.TrainingArguments
  lightning:
    max_steps: 450000
    accelerator: gpu
    devices: -1
    num_nodes: 1
    progress_bar_refresh_rate: 50
    val_check_interval: 10000
    limit_val_batches: 20
    num_sanity_val_steps: 0
    default_root_dir: '${oc.env:SAVE_DIR, .}'
  seed: -1
  batch_size: 8
  num_workers: 4
  learning_rate: 2e-4
  adam_eps: 1e-8
  adam_weight_decay: 1e-2
  warmup_steps: 2000
  prev_v_num: 0
  save_every_min: 60

datasets:
  _target_: definitions.TrainingDatasetsInfo
  selected:
  - image
  - vl
  - text
  image:
    _target_: definitions.ImageFolderInfo
    train_root: ${oc.env:IMAGENET_TRAIN, /datasets/imagenet/uncompressed_train}
    val_root: ${oc.env:IMAGENET_VAL, /datasets/imagenet/uncompressed_val}
  text:
    _target_: definitions.TrainingSingleDatasetInfo
    train:
      - _target_: definitions.HFDatasetInfo
        key: wikitext
        subset: wikitext-103-raw-v1
  vl:
    _target_: definitions.TrainingYFCCDatasetInfo
    metadata_path: ${oc.env:YFCC_META, .}
    image_root: ${oc.env:YFCC_IMAGE, .}
