# Note that in original FLAVA paper, only Logistic Regression numbers were provided for image datasets.
_target_: definitions.FLAVAArguments
training:
  _target_: definitions.TrainingArguments
  lightning:
    max_steps: 33112
    gpus: 8
    progress_bar_refresh_rate: 50
    val_check_interval: 1.0
    num_sanity_val_steps: 10
  seed: -1
  batch_size: 16
  num_workers: 4
  learning_rate: 1e-5
  adam_eps: 1e-6
  adam_weight_decay: 0.1
  adam_betas:
  - 0.9
  - 0.98
  warmup_steps: 1986
  metrics: ["accuracy", "F1"]


datasets:
  _target_: definitions.TrainingDatasetsInfo
  selected:
  - text
  num_classes: 2
  text:
    _target_: definitions.TrainingSingleDatasetInfo
    train:
      - _target_: definitions.HFDatasetInfo
        key: glue
        subset: qqp
    datamodule_extra_kwargs:
      text_columns: ["question1", "question2"]

model:
  _target_: definitions.ModelArguments
  pretrained_model_key: flava_full